### ISSUE TITLE
Can use llama2 instead of ChatGPT?

### ISSUE THREAD

**Issue by hhy-joseph** [silvanmelchior/IncognitoPilot#2]
By any chance we could change the llm here to llama2 or other llm? Thank you!

**Comment by silvanmelchior** [comment]
Hi, yes, I'm actually working on that ;)

**Comment by hhy-joseph** [comment]
Thank you so much!

**Comment by micaelzudo** [comment]
i saw you just upped the support for llama, can we use it? thanks

**Comment by silvanmelchior** [comment]
Hey, I haven't documented yet how to use it and it's still on the dev branch, the newest changes are also not released yet. Please wait a bit more, I hope to finish by this week, should have some free time towards the end of it.

**Comment by silvanmelchior** [comment]
Also to adjust your expectations: Even though I really like llama 2, it unfortunately works much worse than GPT-4 for this task. The tool-finetuning and even interpreter-finetuning from OpenAI helped a lot!

**Comment by micaelzudo** [comment]
I intend to use it with WizardCoder Llama 2! Or any top notch llama 2 coder LLM. Suggestions? For Llama2 Coding LLMS? Thanks you and amazing program by the way, tank you for letting me out of the hands of OpenAI  Enviado do Email para Windows De: silvanmelchiorEnviado:segunda-feira, 14 de agosto de 2023 03:37Para: silvanmelchior/IncognitoPilotCc:micaelzudo; CommentAssunto: Re: [silvanmelchior/IncognitoPilot] Can use llama2 instead of ChatGPT? (Issue #2) Hey, I haven't documented yet how to use it and it's still on the dev branch, the newest changes are also not released yet. Please wait a bit more, I hope to finish by this week, should have some free time towards the end of it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> Não contém vírus.www.avast.com

**Comment by micaelzudo** [comment]
Man i will test OpenAI aswell then, i dont know how expensive it will be for my DevOps i live in brazil and dont know how much 0.08 cents a prompt will cost. Enviado do Email para Windows De: silvanmelchiorEnviado:segunda-feira, 14 de agosto de 2023 03:38Para: silvanmelchior/IncognitoPilotCc:micaelzudo; CommentAssunto: Re: [silvanmelchior/IncognitoPilot] Can use llama2 instead of ChatGPT? (Issue #2) Also to adjust your expectations: Even though I really like llama 2, it unfortunately works much worse than GPT-4 for this task. The tool-finetuning and even interpreter-finetuning from OpenAI helped a lot!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> Não contém vírus.www.avast.com

**Comment by silvanmelchior** [comment]
So my whole development and testing costed me like less than 5 dollars ;). If it's about money, you will for sure end up spending more on power consumption with llama, you will need to use the 70B model for sure

**Comment by micaelzudo** [comment]
Allright, i will get my shit up to pay for open AI bills then. I live in Brazil so, i paid to use code interpreter, but i cant do anything much, only, only today ive managed to run plug-ins + noteable, that is running tensorflow now, but i cant do anything of the work cause of hardware limitations, so i got stuck, if i knew i would just have got open API. What do you think its better, Chatgpt PLUS or OpenAI API? Generally wise .Thank you for IcognitoPilot again, goodbye and good work man. Enviado do Email para Windows De: silvanmelchiorEnviado:segunda-feira, 14 de agosto de 2023 03:41Para: silvanmelchior/IncognitoPilotCc:micaelzudo; CommentAssunto: Re: [silvanmelchior/IncognitoPilot] Can use llama2 instead of ChatGPT? (Issue #2) So my whole development and testing costed me like less than 5 dollars ;). If it's about money, you will for sure end up spending more on power consumption with llama, you will need to use the 70B model for sure—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> Não contém vírus.www.avast.com

**Comment by silvanmelchior** [comment]
Here you go ;)
