### ISSUE TITLE
Support models larger than 8K

### ISSUE THREAD

**Issue by TheDataVoyager** [silvanmelchior/IncognitoPilot#27]
It will be great to support inputs larger than 8K tokens for GPT-35-16K and GPT-4-32K.

Thanks

**Comment by silvanmelchior** [comment]
Hi, not sure if I understand the question, but you should be able to use these models: https://github.com/silvanmelchior/IncognitoPilot#change-model

**Comment by TheDataVoyager** [comment]
Hi, 

The larger token models were working (by following the link above) if the conversations used less than 8K tokens. 

For both the models I outlined, when using a query larger than 8K (I tested with 8.7K) it hung. The prompt disappeared instead of providing an answer. 

As an example, I asked it to take the input (8.7K tokens) and generate a file with that content.

**Comment by silvanmelchior** [comment]
So interestingly, when I try it with gpt-3.5-turbo-16k, and have a long request, then the model starts to output wrong function call arguments. So it should output `{code: "<python-code>"}`, but it actually outputs the python code directly. The backend then cannot parse this, because it's no valid JSON.

We could try to just assume that it's the code, if the JSON is invalid, but I'm not sure how stable it is.

So far I would just see it as a limitation of the models, maybe future versions will overcome this.
